# Generated by Django 4.0.4 on 2022-05-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='users',
            new_name='user',
        ),
    ]
