# Generated by Django 4.0.4 on 2022-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_likepost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
