# Generated by Django 4.0.4 on 2022-05-26 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_post_comment_count_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.AddField(
            model_name='likepost',
            name='value',
            field=models.CharField(blank=True, default='Like', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
