# Generated by Django 4.0.4 on 2022-05-27 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_alter_likepost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.AddField(
            model_name='likepost',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
