# Generated by Django 4.0.4 on 2022-05-28 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_request',
            field=models.ManyToManyField(blank=True, null=True, related_name='friend_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
